version: '3.4'

services:
  server:
    image: server
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  client:
    image: client
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 80:80
